/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

/**
 *
 * @author PASANMAHEE 2019.1.6
 */
import Models.AdminNewUsernamePass_Models;
import DataControls.AdminNewUsernamePass_DB;
import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JOptionPane;

public class AdminNewUserPass extends javax.swing.JFrame {

    /**
     * Creates new form AdminNewUserPass
     */
    String tableName;
    String columnName;

    public AdminNewUserPass() {
        initComponents();
        Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width / 2 - getWidth() / 2, size.height / 2 - getHeight() / 2);

        this.getRootPane().setDefaultButton(btn_ChangeUserNamePassword1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txt_NewUsername = new javax.swing.JTextField();
        txt_newPassword = new javax.swing.JPasswordField();
        btn_ChangeUserNamePassword = new javax.swing.JButton();
        txt_oldUsername = new javax.swing.JTextField();
        txt_oldPassword = new javax.swing.JPasswordField();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt_NewUsername1 = new javax.swing.JTextField();
        txt_newPassword1 = new javax.swing.JPasswordField();
        btn_ChangeUserNamePassword1 = new javax.swing.JButton();
        txt_oldUsername1 = new javax.swing.JTextField();
        txt_oldPassword1 = new javax.swing.JPasswordField();
        jButton4 = new javax.swing.JButton();

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/suwasetha_pharmacy/Back.png"))); // NOI18N
        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(0, 153, 153));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/suwasetha_pharmacy/Login100x100.png"))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(133, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(126, 126, 126))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(185, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(171, 171, 171))
        );

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/suwasetha_pharmacy/Pharmacy.png"))); // NOI18N

        txt_NewUsername.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txt_NewUsername.setForeground(new java.awt.Color(51, 51, 51));
        txt_NewUsername.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_NewUsername.setText("New Username");

        txt_newPassword.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txt_newPassword.setForeground(new java.awt.Color(51, 51, 51));
        txt_newPassword.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_newPassword.setText("jPasswordField1");

        btn_ChangeUserNamePassword.setBackground(new java.awt.Color(0, 204, 204));
        btn_ChangeUserNamePassword.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btn_ChangeUserNamePassword.setForeground(new java.awt.Color(255, 255, 255));
        btn_ChangeUserNamePassword.setText("CHANGE");
        btn_ChangeUserNamePassword.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_ChangeUserNamePassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ChangeUserNamePasswordActionPerformed(evt);
            }
        });

        txt_oldUsername.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txt_oldUsername.setForeground(new java.awt.Color(51, 51, 51));
        txt_oldUsername.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_oldUsername.setText("Old Username");

        txt_oldPassword.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txt_oldPassword.setForeground(new java.awt.Color(51, 51, 51));
        txt_oldPassword.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_oldPassword.setText("jPasswordField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        jPanel4.setBackground(new java.awt.Color(0, 153, 153));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/suwasetha_pharmacy/Login100x100.png"))); // NOI18N

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("ADMINISTRATOR LOGIN");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(81, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(126, 126, 126))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(65, 65, 65))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(200, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addGap(141, 141, 141))
        );

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/suwasetha_pharmacy/Pharmacy.png"))); // NOI18N

        txt_NewUsername1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txt_NewUsername1.setForeground(new java.awt.Color(51, 51, 51));
        txt_NewUsername1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_NewUsername1.setText("New Username");

        txt_newPassword1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txt_newPassword1.setForeground(new java.awt.Color(51, 51, 51));
        txt_newPassword1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_newPassword1.setText("jPasswordField1");

        btn_ChangeUserNamePassword1.setBackground(new java.awt.Color(0, 204, 204));
        btn_ChangeUserNamePassword1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btn_ChangeUserNamePassword1.setForeground(new java.awt.Color(255, 255, 255));
        btn_ChangeUserNamePassword1.setText("CHANGE");
        btn_ChangeUserNamePassword1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_ChangeUserNamePassword1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ChangeUserNamePassword1ActionPerformed(evt);
            }
        });

        txt_oldUsername1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txt_oldUsername1.setForeground(new java.awt.Color(51, 51, 51));
        txt_oldUsername1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_oldUsername1.setText("Old Username");

        txt_oldPassword1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txt_oldPassword1.setForeground(new java.awt.Color(51, 51, 51));
        txt_oldPassword1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_oldPassword1.setText("jPasswordField1");

        jButton4.setBackground(new java.awt.Color(0, 204, 204));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/suwasetha_pharmacy/Back.png"))); // NOI18N
        jButton4.setText("Back");
        jButton4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_oldPassword1, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_oldUsername1, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_NewUsername1, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_newPassword1, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_ChangeUserNamePassword1, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 63, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(txt_oldUsername1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_oldPassword1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(txt_NewUsername1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_newPassword1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_ChangeUserNamePassword1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(95, 95, 95)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Login objLogin = new Login();
        objLogin.setVisible(true);

        this.hide();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btn_ChangeUserNamePasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ChangeUserNamePasswordActionPerformed


    }//GEN-LAST:event_btn_ChangeUserNamePasswordActionPerformed

    private void btn_ChangeUserNamePassword1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ChangeUserNamePassword1ActionPerformed

        tableName = "login";
        columnName = "username";

        String oldUsername = txt_oldUsername1.getText();
        String oldPassword = txt_oldPassword1.getText();
        String newUsername = txt_NewUsername1.getText();
        String newPassword = txt_newPassword1.getText();

        AdminNewUsernamePass_Models objAdminNewUsernamePass_Models1 = new AdminNewUsernamePass_Models();
        objAdminNewUsernamePass_Models1.setoldUsername(oldUsername);

        AdminNewUsernamePass_DB objAdminNewUsernamePass_DB1 = new AdminNewUsernamePass_DB();
        Boolean rs1 = objAdminNewUsernamePass_DB1.getOldUsernameDetails(objAdminNewUsernamePass_Models1);

        AdminNewUsernamePass_Models objAdminNewUsernamePass_Models2 = new AdminNewUsernamePass_Models();
        objAdminNewUsernamePass_Models2.setoldPassword(oldPassword);

        AdminNewUsernamePass_DB objAdminNewUsernamePass_DB2 = new AdminNewUsernamePass_DB();
        Boolean rs2 = objAdminNewUsernamePass_DB2.getOldPasswordDetails(objAdminNewUsernamePass_Models2);
        if (rs1 == false) {
            if (rs2 == false) {
                AdminNewUsernamePass_Models objAdminNewUsernamePass_Models4 = new AdminNewUsernamePass_Models();
                objAdminNewUsernamePass_Models4.setnewUsername(newUsername);
                objAdminNewUsernamePass_Models4.setnewPassword(newPassword);

                AdminNewUsernamePass_DB objNewUsernamePassword_DB4 = new AdminNewUsernamePass_DB();
                int x = objNewUsernamePassword_DB4.insertUsernamePassword(objAdminNewUsernamePass_Models4);

                if (x == 1) {

                    AdminNewUsernamePass_Models objAdminNewUsernamePass_Models3 = new AdminNewUsernamePass_Models();
                    objAdminNewUsernamePass_Models3.setoldUsername(oldUsername);

                    AdminNewUsernamePass_DB objNewUsernamePassword_DB3 = new AdminNewUsernamePass_DB();
                    int y = objNewUsernamePassword_DB3.deleteSales(objAdminNewUsernamePass_Models3);

                    if (y == 1) {

                        JOptionPane.showMessageDialog(null, "Username and Password changed successfull ");
                    } else {
                        JOptionPane.showMessageDialog(null, "Username and Password not changed ");
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Username already exist");
                }
            } else {
            }

        } else {

        }

        Main objMain = new Main();
        objMain.setVisible(true);

        this.hide();

    }//GEN-LAST:event_btn_ChangeUserNamePassword1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        Main objMain = new Main();
        objMain.setVisible(true);
        this.hide();
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminNewUserPass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminNewUserPass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminNewUserPass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminNewUserPass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminNewUserPass().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_ChangeUserNamePassword;
    private javax.swing.JButton btn_ChangeUserNamePassword1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField txt_NewUsername;
    private javax.swing.JTextField txt_NewUsername1;
    private javax.swing.JPasswordField txt_newPassword;
    private javax.swing.JPasswordField txt_newPassword1;
    private javax.swing.JPasswordField txt_oldPassword;
    private javax.swing.JPasswordField txt_oldPassword1;
    private javax.swing.JTextField txt_oldUsername;
    private javax.swing.JTextField txt_oldUsername1;
    // End of variables declaration//GEN-END:variables
}
