/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import javax.swing.JFrame;
import Models.Customer_Models;
import DataControls.Customer_DB;
import java.awt.Image;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import net.proteanit.sql.DbUtils;
import org.opencv.core.Core;

/**
 *
 * @author PASANMAHEE 2018.12.19
 */
public class Customer_Views extends javax.swing.JFrame {

    Connection conn;
    PreparedStatement pst;
    ResultSet rs;

    String columnname;
    String tableName;
    String s; //Path that image exists
    byte[] customerImage;

    /**
     * Creates new form Customer_Views
     */
    public Customer_Views() {
        initComponents();
        JFrame frame = new JFrame();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        frame.setUndecorated(true);

        loadCustomerTable();
        this.getRootPane().setDefaultButton(btn_AddToCustomer);

    }

    private void loadCustomerTable() {
        tableName = "customer";

        Customer_Models objCustomer_Models = new Customer_Models();
        objCustomer_Models.setCustomerDetails(tableName);

        Customer_DB objCustomer_DB = new Customer_DB();
        ResultSet rs = objCustomer_DB.loadCustomerTable(objCustomer_Models);
        try {
            if (rs.next()) {

                tbl_customer.setModel(DbUtils.resultSetToTableModel(rs));
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "No Customer Table Found");
        }

    }

    private void loadImage() {

        String getCustomerID = txt_customerID.getText();
        try {

            Customer_Models objCustomer_Models = new Customer_Models();
            objCustomer_Models.setCustomerID(getCustomerID);
            Customer_DB objCustomer_DB = new Customer_DB();
            ResultSet rs = objCustomer_DB.loadImage(objCustomer_Models);

            if (rs.next()) {
                byte[] imgData = rs.getBytes("Image");
                ImageIcon image = new ImageIcon(imgData);
                Image im = image.getImage();
                Image myimg = im.getScaledInstance(lbl_customerImage.getWidth(), lbl_customerImage.getHeight(), Image.SCALE_SMOOTH);
                ImageIcon newImage = new ImageIcon(myimg);
                lbl_customerImage.setIcon(newImage);

            } else {
                //JOptionPane.showMessageDialog(null, "No Image Data");

            }

        } catch (Exception e) {
            ImageIcon image = new ImageIcon("E:\\HNDJava\\Suwasetha_Pharmacy\\src\\suwasetha_pharmacy\\profilePic.png");
            lbl_customerImage.setIcon(image);
        }

    }

    private void loadLoyaltyCard() {

        String strLoyaltyCardFees = txt_loyaltyCard.getText();
        int intLoyaltyCardFees = Integer.parseInt(strLoyaltyCardFees);

        if (intLoyaltyCardFees >= 200) {
            ImageIcon image = new ImageIcon("E:\\HNDJava\\Suwasetha_Pharmacy\\src\\suwasetha_pharmacy\\LoyaltyCardyes.png");
            lbl_loyaltyCard.setIcon(image);

        } else {
            ImageIcon image = new ImageIcon("E:\\HNDJava\\Suwasetha_Pharmacy\\src\\suwasetha_pharmacy\\LoyaltyCardno.png");
            lbl_loyaltyCard.setIcon(image);
        }

    }

    //used to browse images fit in the Jlable correctely 
    private ImageIcon ResizeImage(String imgPath) {
        ImageIcon MyImage = new ImageIcon(imgPath);
        Image img = MyImage.getImage();
        Image newImage = img.getScaledInstance(lbl_customerImage.getWidth(), lbl_customerImage.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon image = new ImageIcon(newImage);
        return image;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lbl_customerImage = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btn_AddToCustomer = new javax.swing.JButton();
        btn_UpdateCustomer = new javax.swing.JButton();
        btn_DeleteFromCustomer = new javax.swing.JButton();
        btn_Clear = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_medicalHistory = new javax.swing.JTextArea();
        txt_loyaltyCard = new javax.swing.JTextField();
        txt_Email = new javax.swing.JTextField();
        txt_Age = new javax.swing.JTextField();
        txt_TelephoneNo = new javax.swing.JTextField();
        txt_address = new javax.swing.JTextField();
        txt_customerName = new javax.swing.JTextField();
        txt_customerID = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        btn_openCamera = new javax.swing.JButton();
        btn_SendEmail = new javax.swing.JButton();
        btn_browseImage = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lbl_loyaltyCard = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        btn_UpdateImage = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        rb_customerID = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        rb_customerName = new javax.swing.JRadioButton();
        rb_address = new javax.swing.JRadioButton();
        rb_age = new javax.swing.JRadioButton();
        txt_search = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_customer = new javax.swing.JTable();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel4.setBackground(new java.awt.Color(51, 51, 51));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/suwasetha_pharmacy/Pharmacy.png"))); // NOI18N

        lbl_customerImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/suwasetha_pharmacy/profilePic.png"))); // NOI18N
        lbl_customerImage.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Customer ID");

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Name");

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Address");

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Telephone No");

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Email");

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Age");

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Loyalty Card Fees");

        btn_AddToCustomer.setBackground(new java.awt.Color(153, 153, 153));
        btn_AddToCustomer.setForeground(new java.awt.Color(0, 0, 0));
        btn_AddToCustomer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/suwasetha_pharmacy/Add.png"))); // NOI18N
        btn_AddToCustomer.setText("ADD");
        btn_AddToCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AddToCustomerActionPerformed(evt);
            }
        });

        btn_UpdateCustomer.setBackground(new java.awt.Color(153, 153, 153));
        btn_UpdateCustomer.setForeground(new java.awt.Color(0, 0, 0));
        btn_UpdateCustomer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/suwasetha_pharmacy/Update.png"))); // NOI18N
        btn_UpdateCustomer.setText("UPDATE");
        btn_UpdateCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_UpdateCustomerActionPerformed(evt);
            }
        });

        btn_DeleteFromCustomer.setBackground(new java.awt.Color(153, 153, 153));
        btn_DeleteFromCustomer.setForeground(new java.awt.Color(0, 0, 0));
        btn_DeleteFromCustomer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/suwasetha_pharmacy/Delete.png"))); // NOI18N
        btn_DeleteFromCustomer.setText("DELETE");
        btn_DeleteFromCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_DeleteFromCustomerActionPerformed(evt);
            }
        });

        btn_Clear.setBackground(new java.awt.Color(153, 153, 153));
        btn_Clear.setForeground(new java.awt.Color(0, 0, 0));
        btn_Clear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/suwasetha_pharmacy/Clear.png"))); // NOI18N
        btn_Clear.setText("CLEAR");
        btn_Clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ClearActionPerformed(evt);
            }
        });

        txt_medicalHistory.setBackground(new java.awt.Color(102, 102, 102));
        txt_medicalHistory.setColumns(20);
        txt_medicalHistory.setForeground(new java.awt.Color(255, 255, 255));
        txt_medicalHistory.setRows(5);
        jScrollPane1.setViewportView(txt_medicalHistory);

        txt_loyaltyCard.setBackground(new java.awt.Color(102, 102, 102));
        txt_loyaltyCard.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txt_loyaltyCard.setForeground(new java.awt.Color(255, 255, 255));

        txt_Email.setBackground(new java.awt.Color(102, 102, 102));
        txt_Email.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txt_Email.setForeground(new java.awt.Color(255, 255, 255));

        txt_Age.setBackground(new java.awt.Color(102, 102, 102));
        txt_Age.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txt_Age.setForeground(new java.awt.Color(255, 255, 255));

        txt_TelephoneNo.setBackground(new java.awt.Color(102, 102, 102));
        txt_TelephoneNo.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txt_TelephoneNo.setForeground(new java.awt.Color(255, 255, 255));

        txt_address.setBackground(new java.awt.Color(102, 102, 102));
        txt_address.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txt_address.setForeground(new java.awt.Color(255, 255, 255));

        txt_customerName.setBackground(new java.awt.Color(102, 102, 102));
        txt_customerName.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txt_customerName.setForeground(new java.awt.Color(255, 255, 255));

        txt_customerID.setBackground(new java.awt.Color(102, 102, 102));
        txt_customerID.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txt_customerID.setForeground(new java.awt.Color(255, 255, 255));

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Medical History");

        btn_openCamera.setBackground(new java.awt.Color(153, 153, 153));
        btn_openCamera.setForeground(new java.awt.Color(0, 0, 0));
        btn_openCamera.setIcon(new javax.swing.ImageIcon(getClass().getResource("/suwasetha_pharmacy/cam.png"))); // NOI18N
        btn_openCamera.setText("Open Camera");
        btn_openCamera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_openCameraActionPerformed(evt);
            }
        });

        btn_SendEmail.setBackground(new java.awt.Color(153, 153, 153));
        btn_SendEmail.setForeground(new java.awt.Color(0, 0, 0));
        btn_SendEmail.setIcon(new javax.swing.ImageIcon(getClass().getResource("/suwasetha_pharmacy/SendMail.png"))); // NOI18N
        btn_SendEmail.setText("Send Email");
        btn_SendEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SendEmailActionPerformed(evt);
            }
        });

        btn_browseImage.setBackground(new java.awt.Color(153, 153, 153));
        btn_browseImage.setForeground(new java.awt.Color(0, 0, 0));
        btn_browseImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/suwasetha_pharmacy/Browse.png"))); // NOI18N
        btn_browseImage.setText("Browse Image");
        btn_browseImage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_browseImageActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("CUSTOMER PORTAL");

        lbl_loyaltyCard.setBackground(new java.awt.Color(255, 255, 255));
        lbl_loyaltyCard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/suwasetha_pharmacy/LoyaltyCardno.png"))); // NOI18N

        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Rs.");

        btn_UpdateImage.setForeground(new java.awt.Color(0, 0, 0));
        btn_UpdateImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/suwasetha_pharmacy/Update.png"))); // NOI18N
        btn_UpdateImage.setText("UPDATE IMG");
        btn_UpdateImage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_UpdateImageActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap(113, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txt_customerName, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(btn_Clear, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_DeleteFromCustomer)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_UpdateCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_AddToCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txt_Age, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txt_TelephoneNo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txt_customerID, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel15))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel8))
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txt_Email, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txt_loyaltyCard)
                                    .addComponent(btn_SendEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(btn_openCamera))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                        .addComponent(btn_browseImage)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btn_UpdateImage, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(lbl_loyaltyCard, javax.swing.GroupLayout.Alignment.TRAILING))))
                        .addGap(18, 18, 18)
                        .addComponent(lbl_customerImage, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(6, 6, 6))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(txt_address, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_customerImage, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(25, 25, 25)
                                .addComponent(btn_openCamera, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btn_browseImage, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btn_UpdateImage, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(19, 19, 19)
                                .addComponent(lbl_loyaltyCard, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_customerID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(12, 12, 12)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_customerName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_address, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_TelephoneNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_Age, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_Email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_SendEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_loyaltyCard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel15))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_AddToCustomer)
                            .addComponent(btn_UpdateCustomer)
                            .addComponent(btn_DeleteFromCustomer)
                            .addComponent(btn_Clear))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(jLabel11)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        jPanel5.setBackground(new java.awt.Color(51, 51, 51));

        buttonGroup1.add(rb_customerID);
        rb_customerID.setForeground(new java.awt.Color(255, 255, 255));
        rb_customerID.setText("Customer ID");

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Search Customer details by click on Radio button and type a Keyword in below text field ");

        buttonGroup1.add(rb_customerName);
        rb_customerName.setForeground(new java.awt.Color(255, 255, 255));
        rb_customerName.setText("Customer Name");

        buttonGroup1.add(rb_address);
        rb_address.setForeground(new java.awt.Color(255, 255, 255));
        rb_address.setText("Address");

        buttonGroup1.add(rb_age);
        rb_age.setForeground(new java.awt.Color(255, 255, 255));
        rb_age.setText("Age");

        txt_search.setBackground(new java.awt.Color(0, 153, 153));
        txt_search.setForeground(new java.awt.Color(255, 255, 255));
        txt_search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_searchKeyReleased(evt);
            }
        });

        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/suwasetha_pharmacy/icons8_Search_31px.png"))); // NOI18N

        tbl_customer.setBackground(new java.awt.Color(153, 153, 153));
        tbl_customer.setForeground(new java.awt.Color(255, 255, 255));
        tbl_customer.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_customer.addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                tbl_customerMouseWheelMoved(evt);
            }
        });
        tbl_customer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_customerMouseClicked(evt);
            }
        });
        tbl_customer.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tbl_customerKeyPressed(evt);
            }
        });
        jScrollPane2.setViewportView(tbl_customer);

        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Click on the table, row where you want to edit");

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/suwasetha_pharmacy/Customer.png"))); // NOI18N
        jLabel14.setText("jLabel14");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane2)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(txt_search, javax.swing.GroupLayout.PREFERRED_SIZE, 521, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel12))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(rb_customerID)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rb_customerName)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rb_address)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rb_age))
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 103, Short.MAX_VALUE)
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rb_customerID)
                            .addComponent(rb_customerName)
                            .addComponent(rb_address)
                            .addComponent(rb_age))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_AddToCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AddToCustomerActionPerformed

        try {

            String getCustomerID = txt_customerID.getText();
            String getCustomerName = txt_customerName.getText();
            String getAddress = txt_address.getText();
            String getTelephoneNo = txt_TelephoneNo.getText();
            String getEmail = txt_Email.getText();
            String getStrAge = txt_Age.getText();
            String getLoyaltyCardFees = txt_loyaltyCard.getText();
            String getMedicalHistory = txt_medicalHistory.getText();
            byte[] getImage = customerImage;
            int getIntAge = Integer.parseInt(getStrAge);
            int getIntLoyaltyCardFees = Integer.parseInt(getLoyaltyCardFees);

            Customer_Models objCustomer_Models = new Customer_Models(getCustomerID, getCustomerName, getAddress, getTelephoneNo, getEmail, getIntAge, getIntLoyaltyCardFees, getMedicalHistory);
            objCustomer_Models.setImage(getImage);
            Customer_DB objCustomer_DB = new Customer_DB();
            int x = objCustomer_DB.insertCustomer(objCustomer_Models);

            if (x == 1) {
                JOptionPane.showMessageDialog(null, "Inserted Successfull");

            } else {
                JOptionPane.showMessageDialog(null, "Not Inserted");

            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Please fill all the fields with correct values");

        }
        loadCustomerTable();

    }//GEN-LAST:event_btn_AddToCustomerActionPerformed

    private void btn_UpdateCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_UpdateCustomerActionPerformed
        String getCustomerID = txt_customerID.getText();
        String getCustomerName = txt_customerName.getText();
        String getAddress = txt_address.getText();
        String getTelephoneNo = txt_TelephoneNo.getText();
        String getEmail = txt_Email.getText();
        String getStrAge = txt_Age.getText();
        String getLoyaltyCardFees = txt_loyaltyCard.getText();
        String getMedicalHistory = txt_medicalHistory.getText();
        // byte[] getImage = customerImage;
        int getIntAge = Integer.parseInt(getStrAge);
        int getIntLoyaltyCardFees = Integer.parseInt(getLoyaltyCardFees);

        Customer_Models objCustomer_Models = new Customer_Models(getCustomerID, getCustomerName, getAddress, getTelephoneNo, getEmail, getIntAge, getIntLoyaltyCardFees, getMedicalHistory);
        Customer_DB objCustomer_DB = new Customer_DB();

        int x = objCustomer_DB.updateCustomer(objCustomer_Models);

        if (x == 1) {
            JOptionPane.showMessageDialog(null, "Successfully updated");

        } else {
            JOptionPane.showMessageDialog(null, "Not updated");
        }
        loadCustomerTable();
    }//GEN-LAST:event_btn_UpdateCustomerActionPerformed

    private void btn_DeleteFromCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_DeleteFromCustomerActionPerformed
        String getCustomerID = txt_customerID.getText();

        Customer_Models objCustomer_Models = new Customer_Models();
        objCustomer_Models.setCustomerID(getCustomerID);
        Customer_DB objCustomer_DB = new Customer_DB();

        int x = objCustomer_DB.deleteCustomer(objCustomer_Models);
        if (x == 1) {
            JOptionPane.showMessageDialog(null, "Successfully Deleted");

        } else {
            JOptionPane.showMessageDialog(null, "Not Deleted");
        }
        ImageIcon image = new ImageIcon("E:\\HNDJava\\Suwasetha_Pharmacy\\src\\suwasetha_pharmacy\\profilePic.png");
        lbl_customerImage.setIcon(image);
        loadCustomerTable();
    }//GEN-LAST:event_btn_DeleteFromCustomerActionPerformed

    private void btn_ClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ClearActionPerformed
        txt_address.setText("");
        txt_Age.setText("");
        txt_Email.setText("");
        txt_customerID.setText("");
        txt_loyaltyCard.setText("");
        txt_customerName.setText("");
        txt_medicalHistory.setText("");
        txt_TelephoneNo.setText("");

    }//GEN-LAST:event_btn_ClearActionPerformed

    private void btn_openCameraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_openCameraActionPerformed

        WebCamera objWebCamera = new WebCamera();
        objWebCamera.setVisible(true);
    }//GEN-LAST:event_btn_openCameraActionPerformed

    private void btn_SendEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SendEmailActionPerformed

        String getEmailAddress = txt_Email.getText();

        new EmailPortal(getEmailAddress).setVisible(true);

    }//GEN-LAST:event_btn_SendEmailActionPerformed

    private void btn_browseImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_browseImageActionPerformed

        JFileChooser filechooser = new JFileChooser();
        filechooser.setCurrentDirectory(new File(System.getProperty("user.home")));
        FileNameExtensionFilter filter = new FileNameExtensionFilter("*.IMAGE", "jpg", "png");
        filechooser.addChoosableFileFilter(filter);
        int result = filechooser.showSaveDialog(null);
        if (result == JFileChooser.APPROVE_OPTION) {
            File selectedFile = filechooser.getSelectedFile();
            String path = selectedFile.getAbsolutePath();
            lbl_customerImage.setIcon(ResizeImage(path));
            s = path;

            try {
                File image = new File(s);
                FileInputStream fis = new FileInputStream(image);
                ByteArrayOutputStream bos = new ByteArrayOutputStream();
                byte[] buf = new byte[2000000];//Image size in bytes 
                for (int readNum; (readNum = fis.read(buf)) != -1;) {
                    bos.write(buf, 0, readNum);
                }
                customerImage = bos.toByteArray();

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Your Image is too large");
            }

        } else if (result == JFileChooser.CANCEL_OPTION) {
            JOptionPane.showMessageDialog(null, "No Data");
        }

    }//GEN-LAST:event_btn_browseImageActionPerformed

    private void txt_searchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_searchKeyReleased
        Customer_Models objCustomer_Models = new Customer_Models();
        String value = txt_search.getText();
        Customer_DB objCustomer_DB = new Customer_DB();

        if (rb_customerID.isSelected()) {

            objCustomer_Models.setCustomerID(value);
        } else if (rb_customerName.isSelected()) {

            objCustomer_Models.setCustomerName(value);
        } else if (rb_address.isSelected()) {

            objCustomer_Models.setAddress(value);
        } else if (rb_age.isSelected()) {
            int intValue = Integer.parseInt(value);
            objCustomer_Models.setAge(intValue);
        } else {
            JOptionPane.showMessageDialog(null, "Please select a Button before you search");
        }
        ResultSet rs = objCustomer_DB.getSearchDetails(objCustomer_Models);
        tbl_customer.setModel(DbUtils.resultSetToTableModel(rs));

    }//GEN-LAST:event_txt_searchKeyReleased

    private void tbl_customerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_customerMouseClicked

        int row = tbl_customer.getSelectedRow();
        String tableClick = tbl_customer.getModel().getValueAt(row, 0).toString();

        Customer_Models objCustomer_Models = new Customer_Models();
        objCustomer_Models.setCustomerID(tableClick);
        Customer_DB objCustomer_DB = new Customer_DB();
        ResultSet rs = objCustomer_DB.loadCustomerTableID(objCustomer_Models);
        try {
            if (rs.next()) {

                txt_customerID.setText(rs.getString("Customer_ID"));
                txt_address.setText(rs.getString("Address"));
                int intAge = rs.getInt("Age");
                String strAge = String.valueOf(intAge);
                txt_Age.setText(strAge);
                int intLoyaltyCardFees = rs.getInt("Loyalty_card_fees");
                String strLoyaltyCardFees = String.valueOf(intLoyaltyCardFees);
                txt_loyaltyCard.setText(strLoyaltyCardFees);
                txt_customerName.setText(rs.getString("Customer_Name"));
                txt_medicalHistory.setText(rs.getString("Medical_History"));
                txt_TelephoneNo.setText(rs.getString("Telephone_No"));
                txt_Email.setText(rs.getString("Email"));

            } else {
                JOptionPane.showMessageDialog(null, "Error");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        loadImage();
        loadLoyaltyCard();
    }//GEN-LAST:event_tbl_customerMouseClicked

    private void btn_UpdateImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_UpdateImageActionPerformed
        byte[] getImage = customerImage;
        String customerID = txt_customerID.getText();

        Customer_Models objCustomer_Models = new Customer_Models();
        objCustomer_Models.setImage(getImage);
        objCustomer_Models.setCustomerID(customerID);

        Customer_DB objCustomer_DB = new Customer_DB();
        int x = objCustomer_DB.updateImage(objCustomer_Models);

        if (x == 1) {
            JOptionPane.showMessageDialog(null, "Successfully updated");

        } else {
            JOptionPane.showMessageDialog(null, "Not updated");
        }
        loadCustomerTable();


    }//GEN-LAST:event_btn_UpdateImageActionPerformed

    private void tbl_customerKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbl_customerKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_tbl_customerKeyPressed

    private void tbl_customerMouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_tbl_customerMouseWheelMoved


    }//GEN-LAST:event_tbl_customerMouseWheelMoved

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        System.loadLibrary(Core.NATIVE_LIBRARY_NAME);
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Customer_Views.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Customer_Views.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Customer_Views.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Customer_Views.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Customer_Views().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_AddToCustomer;
    private javax.swing.JButton btn_Clear;
    private javax.swing.JButton btn_DeleteFromCustomer;
    private javax.swing.JButton btn_SendEmail;
    private javax.swing.JButton btn_UpdateCustomer;
    private javax.swing.JButton btn_UpdateImage;
    private javax.swing.JButton btn_browseImage;
    private javax.swing.JButton btn_openCamera;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbl_customerImage;
    private javax.swing.JLabel lbl_loyaltyCard;
    private javax.swing.JRadioButton rb_address;
    private javax.swing.JRadioButton rb_age;
    private javax.swing.JRadioButton rb_customerID;
    private javax.swing.JRadioButton rb_customerName;
    private javax.swing.JTable tbl_customer;
    private javax.swing.JTextField txt_Age;
    private javax.swing.JTextField txt_Email;
    private javax.swing.JTextField txt_TelephoneNo;
    private javax.swing.JTextField txt_address;
    private javax.swing.JTextField txt_customerID;
    private javax.swing.JTextField txt_customerName;
    private javax.swing.JTextField txt_loyaltyCard;
    private javax.swing.JTextArea txt_medicalHistory;
    private javax.swing.JTextField txt_search;
    // End of variables declaration//GEN-END:variables
}
