/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JFrame;
import Models.DrugCategories_Models;
import DataControls.DrugCategories_DB;
import Models.Supplier_Models;
import DataControls.Supplier_DB;
import java.awt.Color;
import java.awt.Component;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.TableCellRenderer;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author PASANMAHEE 2018.12.24
 */
public class DrugCategories_Views extends javax.swing.JFrame {

    Connection conn;
    PreparedStatement pst;
    ResultSet rs;

    String columnname;
    String tableName;

    /**
     * Creates new form DrugCategories_Views
     */
    public DrugCategories_Views() {
        initComponents();
        JFrame frame = new JFrame();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        frame.setUndecorated(true);

        loadDrugCategoriesTable();
    

    }

    private void loadDrugCategoriesTable() {
        tableName = "drug_categories";
        DrugCategories_Models objDrugCategories_Models = new DrugCategories_Models();
        objDrugCategories_Models.setDrugCategoryDetails(tableName);
        DrugCategories_DB objDrugCategories_DB = new DrugCategories_DB();
        ResultSet rs = objDrugCategories_DB.loadDrugCategoryTable(objDrugCategories_Models);

        try {
            if (rs.next()) {
                tbl_DrugCategories.setModel(DbUtils.resultSetToTableModel(rs));

            } else {
                JOptionPane.showMessageDialog(null, "No Drug Categories Table Found");
            }

        } catch (Exception e) {
        }

    }

    private void loadSupplierTableWhenClicked() {
        String supplierNIC = txt_supplierNIC.getText();

        Supplier_Models objSupplier_Models = new Supplier_Models();
        objSupplier_Models.setSupplierNIC(supplierNIC);
        Supplier_DB objSupplier_DB = new Supplier_DB();
        ResultSet rs = objSupplier_DB.loadSupplierTableID(objSupplier_Models);

        try {

            if (rs.next()) {
                txt_SupplierModeNIC.setText(rs.getString("NIC"));
                txt_SupplierModeBusinessName.setText(rs.getString("Business_name"));
                txt_SupplierModeEmail.setText(rs.getString("Email"));
                txt_supplierModeTelephone.setText(rs.getString("Telephone_no"));
                int intGetRating = rs.getInt("Rating");

                if (intGetRating == 1) {
                    ImageIcon image = new ImageIcon("E:\\HNDJava\\Suwasetha_Pharmacy\\src\\suwasetha_pharmacy\\1.png");
                    lbl_Rating.setIcon(image);

                } else if (intGetRating == 2) {
                    ImageIcon image = new ImageIcon("E:\\HNDJava\\Suwasetha_Pharmacy\\src\\suwasetha_pharmacy\\2.png");
                    lbl_Rating.setIcon(image);
                } else if (intGetRating == 3) {
                    ImageIcon image = new ImageIcon("E:\\HNDJava\\Suwasetha_Pharmacy\\src\\suwasetha_pharmacy\\3.png");
                    lbl_Rating.setIcon(image);

                } else if (intGetRating == 4) {
                    ImageIcon image = new ImageIcon("E:\\HNDJava\\Suwasetha_Pharmacy\\src\\suwasetha_pharmacy\\4.png");
                    lbl_Rating.setIcon(image);

                } else {

                    ImageIcon image = new ImageIcon("E:\\HNDJava\\Suwasetha_Pharmacy\\src\\suwasetha_pharmacy\\5.png");
                    lbl_Rating.setIcon(image);

                }

            }

        } catch (Exception e) {
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_DrugName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_BrandName = new javax.swing.JTextField();
        txt_supplierNIC = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_BuyingPrice = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_sellingPrice = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txt_profit = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txt_remainInStock = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        cmb_DrugCategories = new javax.swing.JComboBox<>();
        btn_AddToDrugCategories = new javax.swing.JButton();
        btn_UpdateDrugCategories = new javax.swing.JButton();
        btn_DeleteFromDrugCategories = new javax.swing.JButton();
        btn_Clear = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        txt_Category = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        txt_ReOrderValue = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_SideEffects = new javax.swing.JTextArea();
        jLabel11 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_DrugCategories = new javax.swing.JTable(){
            @Override
            public Component prepareRenderer(TableCellRenderer renderer,int row,int column ){

                Component c = super.prepareRenderer(renderer, row, column);
                c.setBackground(Color.DARK_GRAY);
                Object stockValue = getModel().getValueAt(row,6);
                int intStockValue = (Integer) stockValue;

                Object reOrderValue = getModel().getValueAt(row,7);
                int intReOrderValue = (Integer) reOrderValue;

                if(intStockValue <intReOrderValue){
                    c.setBackground(Color.RED);
                }
                else if(intStockValue >intReOrderValue){
                    c.setBackground(Color.GREEN);
                }
                else{ c.setBackground(Color.DARK_GRAY);
                }

                return c;
            }

        }
        ;
        rb_Category = new javax.swing.JRadioButton();
        jLabel12 = new javax.swing.JLabel();
        rb_DrugName = new javax.swing.JRadioButton();
        rb_BrandName = new javax.swing.JRadioButton();
        txt_search = new javax.swing.JTextField();
        searchBar = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        txt_SupplierModeNIC = new javax.swing.JTextField();
        txt_SupplierModeEmail = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        btn_SendMail = new javax.swing.JButton();
        txt_SupplierModeBusinessName = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txt_supplierModeTelephone = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        lbl_Rating = new javax.swing.JLabel();
        btn_OpenSupplier = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/suwasetha_pharmacy/Pharmacy.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Drug Categories");

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Drug Name");

        txt_DrugName.setBackground(new java.awt.Color(102, 102, 102));
        txt_DrugName.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txt_DrugName.setForeground(new java.awt.Color(255, 255, 255));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Brand Name");

        txt_BrandName.setBackground(new java.awt.Color(102, 102, 102));
        txt_BrandName.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txt_BrandName.setForeground(new java.awt.Color(255, 255, 255));

        txt_supplierNIC.setBackground(new java.awt.Color(102, 102, 102));
        txt_supplierNIC.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txt_supplierNIC.setForeground(new java.awt.Color(255, 255, 255));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Supplier NIC");

        txt_BuyingPrice.setBackground(new java.awt.Color(102, 102, 102));
        txt_BuyingPrice.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txt_BuyingPrice.setForeground(new java.awt.Color(255, 255, 255));
        txt_BuyingPrice.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Buying Price");

        txt_sellingPrice.setBackground(new java.awt.Color(102, 102, 102));
        txt_sellingPrice.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        txt_sellingPrice.setForeground(new java.awt.Color(255, 255, 255));
        txt_sellingPrice.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Selling Price");

        txt_profit.setEditable(false);
        txt_profit.setBackground(new java.awt.Color(51, 51, 51));
        txt_profit.setForeground(new java.awt.Color(255, 255, 255));
        txt_profit.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txt_profit.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txt_profit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_profitActionPerformed(evt);
            }
        });

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Profit");

        txt_remainInStock.setBackground(new java.awt.Color(102, 102, 102));
        txt_remainInStock.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txt_remainInStock.setForeground(new java.awt.Color(0, 0, 0));
        txt_remainInStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_remainInStockActionPerformed(evt);
            }
        });

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Remain in Stock");

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Expiry Date");

        cmb_DrugCategories.setBackground(new java.awt.Color(153, 153, 153));
        cmb_DrugCategories.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ACE inhibitor", "Analgesic", "Anesthetic", "Anabolic steroid", "Antidepressant", "Antibiotics", "Agonist", "Angiotensin II receptor blocker", "Anticoagulant", "Anticonvulsant", "Anti-diabetic medication", "Antiemetic", "Antihistamine", "Anti-inflammatory", "Antihypertensive drug", "Antipsychotic", "Anxiolytic", "Babiturate", "Benzodiazepine", "Beta blocker", "Calcium", "Calcium channel blocker", "Cannabinoid", "Chemotherapy", "Cold medicine", "Corticosteroid", "Depressant", "Dietary supplement", "Dissociative", "Diuretic", "Ensyme", "Enzyme inhibitor", "Hallucinogen", "Hormone", "Hypnotic", "Inhalant", "Insulin", "Muscle relaxant", "Narcotic", "Nonsteroidal anti-inflammatory drug", "Opioid", "Opiate", "Psychoactive drug", "Receptor antagonist", "Sedative", "Solvent in chemical reactions", "Steroid", "Stimulant", "Vaccine", "Vitamin" }));
        cmb_DrugCategories.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                cmb_DrugCategoriesMouseMoved(evt);
            }
        });
        cmb_DrugCategories.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                cmb_DrugCategoriesPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        cmb_DrugCategories.addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                cmb_DrugCategoriesMouseWheelMoved(evt);
            }
        });
        cmb_DrugCategories.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmb_DrugCategoriesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cmb_DrugCategoriesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cmb_DrugCategoriesMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cmb_DrugCategoriesMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                cmb_DrugCategoriesMouseReleased(evt);
            }
        });

        btn_AddToDrugCategories.setBackground(new java.awt.Color(153, 153, 153));
        btn_AddToDrugCategories.setIcon(new javax.swing.ImageIcon(getClass().getResource("/suwasetha_pharmacy/Add.png"))); // NOI18N
        btn_AddToDrugCategories.setText("ADD");
        btn_AddToDrugCategories.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AddToDrugCategoriesActionPerformed(evt);
            }
        });

        btn_UpdateDrugCategories.setBackground(new java.awt.Color(153, 153, 153));
        btn_UpdateDrugCategories.setIcon(new javax.swing.ImageIcon(getClass().getResource("/suwasetha_pharmacy/Update.png"))); // NOI18N
        btn_UpdateDrugCategories.setText("UPDATE");
        btn_UpdateDrugCategories.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_UpdateDrugCategoriesActionPerformed(evt);
            }
        });

        btn_DeleteFromDrugCategories.setBackground(new java.awt.Color(153, 153, 153));
        btn_DeleteFromDrugCategories.setIcon(new javax.swing.ImageIcon(getClass().getResource("/suwasetha_pharmacy/Delete.png"))); // NOI18N
        btn_DeleteFromDrugCategories.setText("DELETE");
        btn_DeleteFromDrugCategories.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_DeleteFromDrugCategoriesActionPerformed(evt);
            }
        });

        btn_Clear.setBackground(new java.awt.Color(153, 153, 153));
        btn_Clear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/suwasetha_pharmacy/Clear.png"))); // NOI18N
        btn_Clear.setText("CLEAR");
        btn_Clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ClearActionPerformed(evt);
            }
        });

        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Category");

        txt_Category.setBackground(new java.awt.Color(102, 102, 102));
        txt_Category.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txt_Category.setForeground(new java.awt.Color(255, 255, 255));
        txt_Category.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                txt_CategoryMouseMoved(evt);
            }
        });
        txt_Category.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                txt_CategoryMouseReleased(evt);
            }
        });

        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Rs.");

        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Rs.");

        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Rs.");

        jDateChooser1.setDateFormatString("yyyy-MM-dd");

        txt_ReOrderValue.setBackground(new java.awt.Color(102, 102, 102));
        txt_ReOrderValue.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txt_ReOrderValue.setForeground(new java.awt.Color(255, 255, 255));

        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Re-Order Value");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel24))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_DrugName)
                            .addComponent(txt_BrandName)
                            .addComponent(txt_supplierNIC)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(txt_remainInStock, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txt_ReOrderValue, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel8)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel21))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel6)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jLabel22))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel7)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jLabel23)))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txt_profit, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txt_sellingPrice, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                                    .addComponent(txt_BuyingPrice, javax.swing.GroupLayout.Alignment.TRAILING)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel17))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_Category)
                            .addComponent(cmb_DrugCategories, javax.swing.GroupLayout.Alignment.TRAILING, 0, 343, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btn_Clear)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_DeleteFromDrugCategories)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_UpdateDrugCategories)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_AddToDrugCategories, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(cmb_DrugCategories, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel17)
                                    .addComponent(txt_Category, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(19, 19, 19)
                                .addComponent(txt_DrugName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_BrandName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_supplierNIC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(56, 56, 56)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txt_ReOrderValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel24))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txt_remainInStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9))
                                .addGap(31, 31, 31)
                                .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txt_BuyingPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel22))
                                .addGap(11, 11, 11)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txt_sellingPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel23))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel21)
                                            .addComponent(jLabel8)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(8, 8, 8)
                                        .addComponent(txt_profit, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_AddToDrugCategories)
                    .addComponent(btn_UpdateDrugCategories)
                    .addComponent(btn_DeleteFromDrugCategories)
                    .addComponent(btn_Clear))
                .addGap(24, 24, 24))
        );

        jPanel4.setBackground(new java.awt.Color(51, 51, 51));

        txt_SideEffects.setBackground(new java.awt.Color(102, 102, 102));
        txt_SideEffects.setColumns(20);
        txt_SideEffects.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        txt_SideEffects.setForeground(new java.awt.Color(255, 255, 255));
        txt_SideEffects.setRows(5);
        jScrollPane1.setViewportView(txt_SideEffects);

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Side Effects");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(683, 683, 683))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 728, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));

        tbl_DrugCategories.setBackground(new java.awt.Color(153, 153, 153));
        tbl_DrugCategories.setForeground(new java.awt.Color(0, 0, 0));
        tbl_DrugCategories.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_DrugCategories.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_DrugCategoriesMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbl_DrugCategories);

        buttonGroup1.add(rb_Category);
        rb_Category.setForeground(new java.awt.Color(255, 255, 255));
        rb_Category.setText("Category");

        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Search Drug details by click on Radio button and type a Keyword in below text field ");

        buttonGroup1.add(rb_DrugName);
        rb_DrugName.setForeground(new java.awt.Color(255, 255, 255));
        rb_DrugName.setText("Drug Name");

        buttonGroup1.add(rb_BrandName);
        rb_BrandName.setForeground(new java.awt.Color(255, 255, 255));
        rb_BrandName.setText("Brand Name");

        txt_search.setBackground(new java.awt.Color(0, 153, 153));
        txt_search.setForeground(new java.awt.Color(0, 0, 0));
        txt_search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_searchKeyReleased(evt);
            }
        });

        searchBar.setBackground(new java.awt.Color(0, 150, 136));
        searchBar.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        searchBar.setForeground(new java.awt.Color(255, 255, 255));
        searchBar.setBorder(null);

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/suwasetha_pharmacy/icons8_Search_31px.png"))); // NOI18N

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/suwasetha_pharmacy/DrugCategories.png"))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(7, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 729, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(rb_Category)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(rb_DrugName)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(rb_BrandName))
                                    .addComponent(txt_search, javax.swing.GroupLayout.PREFERRED_SIZE, 598, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel19)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(7, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(0, 371, Short.MAX_VALUE)
                    .addComponent(searchBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 372, Short.MAX_VALUE)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(rb_Category)
                                    .addComponent(rb_DrugName)
                                    .addComponent(rb_BrandName))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel19)))
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(0, 216, Short.MAX_VALUE)
                    .addComponent(searchBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 216, Short.MAX_VALUE)))
        );

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));

        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Supplier NIC");

        txt_SupplierModeNIC.setBackground(new java.awt.Color(102, 102, 102));
        txt_SupplierModeNIC.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txt_SupplierModeNIC.setForeground(new java.awt.Color(255, 255, 255));

        txt_SupplierModeEmail.setBackground(new java.awt.Color(102, 102, 102));
        txt_SupplierModeEmail.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txt_SupplierModeEmail.setForeground(new java.awt.Color(255, 255, 255));

        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Email");

        btn_SendMail.setBackground(new java.awt.Color(153, 153, 153));
        btn_SendMail.setIcon(new javax.swing.ImageIcon(getClass().getResource("/suwasetha_pharmacy/SendMail24x24.png"))); // NOI18N
        btn_SendMail.setText("Send Mail");
        btn_SendMail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SendMailActionPerformed(evt);
            }
        });

        txt_SupplierModeBusinessName.setBackground(new java.awt.Color(102, 102, 102));
        txt_SupplierModeBusinessName.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txt_SupplierModeBusinessName.setForeground(new java.awt.Color(255, 255, 255));

        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Business Name");

        txt_supplierModeTelephone.setBackground(new java.awt.Color(102, 102, 102));
        txt_supplierModeTelephone.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txt_supplierModeTelephone.setForeground(new java.awt.Color(255, 255, 255));

        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Telephone No");

        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Rating");

        lbl_Rating.setIcon(new javax.swing.ImageIcon(getClass().getResource("/suwasetha_pharmacy/1.png"))); // NOI18N

        btn_OpenSupplier.setIcon(new javax.swing.ImageIcon(getClass().getResource("/suwasetha_pharmacy/supplier 24x24.png"))); // NOI18N
        btn_OpenSupplier.setText("Open Supplier");
        btn_OpenSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_OpenSupplierActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16)
                    .addComponent(jLabel14)
                    .addComponent(jLabel13)
                    .addComponent(jLabel18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_SupplierModeBusinessName, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(txt_SupplierModeEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 305, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_SendMail))
                    .addComponent(txt_SupplierModeNIC)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lbl_Rating, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_OpenSupplier))
                    .addComponent(txt_supplierModeTelephone))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_SupplierModeNIC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_SupplierModeEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_SendMail, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_SupplierModeBusinessName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_supplierModeTelephone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel18)
                        .addGap(24, 24, 24))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_Rating, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btn_OpenSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_remainInStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_remainInStockActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_remainInStockActionPerformed

    private void tbl_DrugCategoriesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_DrugCategoriesMouseClicked
        int row = tbl_DrugCategories.getSelectedRow();
        String tableClick = tbl_DrugCategories.getModel().getValueAt(row, 1).toString();

        DrugCategories_Models objCategories_Models = new DrugCategories_Models();
        objCategories_Models.setDrugName(tableClick);
        DrugCategories_DB objDrugCategories_DB = new DrugCategories_DB();

        ResultSet rs = objDrugCategories_DB.loadDrugCategoryID(objCategories_Models);
        try {
            if (rs.next()) {

                txt_Category.setText(rs.getString("Category"));
                txt_DrugName.setText(rs.getString("Drug_name"));
                txt_supplierNIC.setText(rs.getString("Supplier_NIC"));
                txt_BrandName.setText(rs.getString("Brand_name"));

                double getdoubleBuyingPrice = rs.getDouble("Buying_price");
                double getdoubleSellingPrice = rs.getDouble("Selling_price");
                int getIntRemainInStock = rs.getInt("Remain_in_stock");
                int getIntreOderValue = rs.getInt("Re_order_value");
                double intProfit = getdoubleSellingPrice - getdoubleBuyingPrice;

                String strBuyingPrice = String.valueOf(getdoubleBuyingPrice);
                String strRemainInStock = String.valueOf(getIntRemainInStock);
                String strReOrderValue = String.valueOf(getIntreOderValue);
                String strSellingPrice = String.valueOf(getdoubleSellingPrice);
                String strProfit = String.valueOf(intProfit);

                txt_BuyingPrice.setText(strBuyingPrice);
                txt_sellingPrice.setText(strSellingPrice);
                txt_profit.setText(strProfit);
                txt_remainInStock.setText(strRemainInStock);
                txt_ReOrderValue.setText(strReOrderValue);
                
                txt_SideEffects.setText(rs.getString("Side_effects"));

                java.util.Date d = rs.getDate("Expiry_date");
                jDateChooser1.setDate(d);

            } else {
                //JOptionPane.showMessageDialog(null, "Error");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        loadSupplierTableWhenClicked();
    }//GEN-LAST:event_tbl_DrugCategoriesMouseClicked

    private void btn_SendMailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SendMailActionPerformed
        String getEmailAddress = txt_SupplierModeEmail.getText();

        new EmailPortal(getEmailAddress).setVisible(true);
    }//GEN-LAST:event_btn_SendMailActionPerformed

    private void btn_AddToDrugCategoriesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AddToDrugCategoriesActionPerformed
        try {
            String brandName = txt_BrandName.getText();
            String buyingPrice = txt_BuyingPrice.getText();
            String category = cmb_DrugCategories.getSelectedItem().toString();
            String drugName = txt_DrugName.getText();

            String sideEffects = txt_SideEffects.getText();
            String remainInStock = txt_remainInStock.getText();
            String sellingPrice = txt_sellingPrice.getText();
            String supplierNIC = txt_supplierNIC.getText();
            String strReorderValue = txt_ReOrderValue.getText();

            double doubleBuyingPrice = Double.parseDouble(buyingPrice);
            double doubleSellingPrice = Double.parseDouble(sellingPrice);
            int intRemainInStock = Integer.parseInt(remainInStock);
            int intReorderValue = Integer.parseInt(strReorderValue);

            java.util.Date d = jDateChooser1.getDate();
            if (d == null) {
                System.out.println("No date specified!");
            } else {
                java.sql.Date sqldate = new java.sql.Date(d.getTime());

                DrugCategories_Models objCategories_Models = new DrugCategories_Models(category, drugName, brandName, supplierNIC, doubleBuyingPrice, doubleSellingPrice, intRemainInStock, intReorderValue, sqldate, sideEffects);
                DrugCategories_DB objDrugCategories_DB = new DrugCategories_DB();

                int x = objDrugCategories_DB.insertDrugCategories(objCategories_Models);
                if (x == 1) {
                    JOptionPane.showMessageDialog(null, "Successfully Inserted");

                } else {
                    JOptionPane.showMessageDialog(null, "Not Inserted");
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Please fill all the fields");
        }
        loadDrugCategoriesTable();


    }//GEN-LAST:event_btn_AddToDrugCategoriesActionPerformed

    private void btn_UpdateDrugCategoriesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_UpdateDrugCategoriesActionPerformed
        String brandName = txt_BrandName.getText();
        String buyingPrice = txt_BuyingPrice.getText();
        String category = txt_Category.getText();
        String drugName = txt_DrugName.getText();
        String strReorderValue = txt_ReOrderValue.getText();

        String sideEffects = txt_SideEffects.getText();
        String remainInStock = txt_remainInStock.getText();
        String sellingPrice = txt_sellingPrice.getText();
        String supplierNIC = txt_supplierNIC.getText();

        double doubleBuyingPrice = Double.parseDouble(buyingPrice);
        double doubleSellingPrice = Double.parseDouble(sellingPrice);
        int intRemainInStock = Integer.parseInt(remainInStock);
        int intReorderValue = Integer.parseInt(strReorderValue);
        try {
            java.util.Date d = jDateChooser1.getDate();
            java.sql.Date sqldate = new java.sql.Date(d.getTime());

            DrugCategories_Models objCategories_Models = new DrugCategories_Models(category, drugName, brandName, supplierNIC, doubleBuyingPrice, doubleSellingPrice, intRemainInStock, intReorderValue, sqldate, sideEffects);
            DrugCategories_DB objDrugCategories_DB = new DrugCategories_DB();

            int x = objDrugCategories_DB.updateDrugCategories(objCategories_Models);

            if (x == 1) {
                JOptionPane.showMessageDialog(null, "Successfully updaeted");

            } else {
                JOptionPane.showMessageDialog(null, "Not updated");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Select Expiry Date");
        }
        loadDrugCategoriesTable();


    }//GEN-LAST:event_btn_UpdateDrugCategoriesActionPerformed

    private void btn_DeleteFromDrugCategoriesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_DeleteFromDrugCategoriesActionPerformed
        String getDrugName = txt_DrugName.getText();

        DrugCategories_Models objCategories_Models = new DrugCategories_Models();
        objCategories_Models.setDrugName(getDrugName);
        DrugCategories_DB objDrugCategories_DB = new DrugCategories_DB();

        int x = objDrugCategories_DB.deleteDrugCategories(objCategories_Models);
        if (x == 1) {
            JOptionPane.showMessageDialog(null, "Successfully Deleted");

        } else {
            JOptionPane.showMessageDialog(null, "Not Deleted");
        }
        loadDrugCategoriesTable();

    }//GEN-LAST:event_btn_DeleteFromDrugCategoriesActionPerformed

    private void btn_ClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ClearActionPerformed
        txt_BrandName.setText("");
        txt_BuyingPrice.setText("");
        txt_Category.setText("");
        txt_DrugName.setText("");
        txt_SideEffects.setText("");
        txt_SupplierModeBusinessName.setText("");
        txt_SupplierModeEmail.setText("");
        txt_SupplierModeNIC.setText("");
        txt_profit.setText("");
        txt_remainInStock.setText("");
        txt_sellingPrice.setText("");
        txt_supplierModeTelephone.setText("");
        txt_supplierNIC.setText("");
        txt_ReOrderValue.setText("");
    }//GEN-LAST:event_btn_ClearActionPerformed

    private void cmb_DrugCategoriesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmb_DrugCategoriesMouseClicked

    }//GEN-LAST:event_cmb_DrugCategoriesMouseClicked

    private void cmb_DrugCategoriesMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmb_DrugCategoriesMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_DrugCategoriesMouseReleased

    private void cmb_DrugCategoriesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmb_DrugCategoriesMouseExited

    }//GEN-LAST:event_cmb_DrugCategoriesMouseExited

    private void cmb_DrugCategoriesMouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_cmb_DrugCategoriesMouseWheelMoved

    }//GEN-LAST:event_cmb_DrugCategoriesMouseWheelMoved

    private void txt_CategoryMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_CategoryMouseReleased

    }//GEN-LAST:event_txt_CategoryMouseReleased

    private void cmb_DrugCategoriesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmb_DrugCategoriesMouseEntered

    }//GEN-LAST:event_cmb_DrugCategoriesMouseEntered

    private void cmb_DrugCategoriesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmb_DrugCategoriesMousePressed

    }//GEN-LAST:event_cmb_DrugCategoriesMousePressed

    private void cmb_DrugCategoriesMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmb_DrugCategoriesMouseMoved

    }//GEN-LAST:event_cmb_DrugCategoriesMouseMoved

    private void txt_CategoryMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_CategoryMouseMoved

    }//GEN-LAST:event_txt_CategoryMouseMoved

    private void cmb_DrugCategoriesPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_cmb_DrugCategoriesPopupMenuWillBecomeInvisible
        String getDrug = cmb_DrugCategories.getSelectedItem().toString();
        txt_Category.setText(getDrug);
    }//GEN-LAST:event_cmb_DrugCategoriesPopupMenuWillBecomeInvisible

    private void txt_searchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_searchKeyReleased
        DrugCategories_Models objCategories_Models = new DrugCategories_Models();
        String value = txt_search.getText();
        DrugCategories_DB objDrugCategories_DB = new DrugCategories_DB();

        if (rb_Category.isSelected()) {

            objCategories_Models.setCategory(value);
        } else if (rb_DrugName.isSelected()) {

            objCategories_Models.setDrugName(value);
        } else if (rb_BrandName.isSelected()) {

            objCategories_Models.setBrandName(value);
        } else {
            JOptionPane.showMessageDialog(null, "Please select a Button before you search");
        }
        ResultSet rs = objDrugCategories_DB.getSearchDetails(objCategories_Models);

        tbl_DrugCategories.setModel(DbUtils.resultSetToTableModel(rs));

    }//GEN-LAST:event_txt_searchKeyReleased

    private void btn_OpenSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_OpenSupplierActionPerformed
        Supplier_Views objSupplier_Views = new Supplier_Views();
        objSupplier_Views.setVisible(true);
        
    }//GEN-LAST:event_btn_OpenSupplierActionPerformed

    private void txt_profitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_profitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_profitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DrugCategories_Views.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DrugCategories_Views.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DrugCategories_Views.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DrugCategories_Views.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DrugCategories_Views().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_AddToDrugCategories;
    private javax.swing.JButton btn_Clear;
    private javax.swing.JButton btn_DeleteFromDrugCategories;
    private javax.swing.JButton btn_OpenSupplier;
    private javax.swing.JButton btn_SendMail;
    private javax.swing.JButton btn_UpdateDrugCategories;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cmb_DrugCategories;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbl_Rating;
    private javax.swing.JRadioButton rb_BrandName;
    private javax.swing.JRadioButton rb_Category;
    private javax.swing.JRadioButton rb_DrugName;
    private javax.swing.JTextField searchBar;
    private javax.swing.JTable tbl_DrugCategories;
    private javax.swing.JTextField txt_BrandName;
    private javax.swing.JTextField txt_BuyingPrice;
    private javax.swing.JTextField txt_Category;
    private javax.swing.JTextField txt_DrugName;
    private javax.swing.JTextField txt_ReOrderValue;
    private javax.swing.JTextArea txt_SideEffects;
    private javax.swing.JTextField txt_SupplierModeBusinessName;
    private javax.swing.JTextField txt_SupplierModeEmail;
    private javax.swing.JTextField txt_SupplierModeNIC;
    private javax.swing.JTextField txt_profit;
    private javax.swing.JTextField txt_remainInStock;
    private javax.swing.JTextField txt_search;
    private javax.swing.JTextField txt_sellingPrice;
    private javax.swing.JTextField txt_supplierModeTelephone;
    private javax.swing.JTextField txt_supplierNIC;
    // End of variables declaration//GEN-END:variables
}
