/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import javax.swing.JFrame;
import Models.Employee_Models;
import DataControls.Employee_DB;
import java.awt.Image;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.lang.reflect.Field;
import java.sql.Blob;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.sql.rowset.serial.SerialBlob;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import net.proteanit.sql.DbUtils;
import org.opencv.core.Core;

/**
 *
 * @author PASANMAHEE 2018.12.17
 */
public class Employee_Views extends javax.swing.JFrame {

    Connection conn;
    PreparedStatement pst;
    ResultSet rs;

    String columnname;
    String tableName;
    String s;//Path that image exists
    byte[] employeeImage;

    /**
     * Creates new form Employee_Views
     */
    public Employee_Views() {
        initComponents();
        JFrame frame = new JFrame();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        frame.setUndecorated(true);

        loadEmployeeTable();

    }

    private void loadEmployeeTable() {
        tableName = "employee";

        Employee_Models objEmployee_Models = new Employee_Models();
        objEmployee_Models.setEmployeeDetails(tableName);

        Employee_DB objEmployee_DB = new Employee_DB();
        ResultSet rs = objEmployee_DB.loadEmployeeTable(objEmployee_Models);
        try {
            if (rs.next()) {

                tbl_employee.setModel(DbUtils.resultSetToTableModel(rs));
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "No Employee Table Found");
        }

    }

    private void loadImage() {

        String getEmployeeID = txt_EmployeeID.getText();
        try {

            Employee_Models objEmployee_Models = new Employee_Models();
            objEmployee_Models.setEmployeeID(getEmployeeID);
            Employee_DB objEmployee_DB = new Employee_DB();
            ResultSet rs = objEmployee_DB.loadImage(objEmployee_Models);

            if (rs.next()) {
                byte[] imgData = rs.getBytes("Image");
                ImageIcon image = new ImageIcon(imgData);
                Image im = image.getImage();
                Image myimg = im.getScaledInstance(lbl_employeeImage.getWidth(), lbl_employeeImage.getHeight(), Image.SCALE_SMOOTH);
                ImageIcon newImage = new ImageIcon(myimg);
                lbl_employeeImage.setIcon(newImage);

            } else {
                

            }

        } catch (Exception e) {
             ImageIcon image = new ImageIcon("E:\\HNDJava\\Suwasetha_Pharmacy\\src\\suwasetha_pharmacy\\profilePic.png");
             lbl_employeeImage.setIcon(image);
        }

    }
//used to browse images fit in the Jlable correctely 

    private ImageIcon ResizeImage(String imgPath) {
        ImageIcon MyImage = new ImageIcon(imgPath);
        Image img = MyImage.getImage();
        Image newImage = img.getScaledInstance(lbl_employeeImage.getWidth(), lbl_employeeImage.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon image = new ImageIcon(newImage);
        return image;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        rb_EmployeeID = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        rb_EmployeeName = new javax.swing.JRadioButton();
        rb_Address = new javax.swing.JRadioButton();
        rb_Age = new javax.swing.JRadioButton();
        txt_search = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_employee = new javax.swing.JTable();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lbl_employeeImage = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btn_AddToEmployee = new javax.swing.JButton();
        btn_UpdateEmployee = new javax.swing.JButton();
        btn_DeleteFromEmployee = new javax.swing.JButton();
        btn_clear = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_Qualifications = new javax.swing.JTextArea();
        txt_Email = new javax.swing.JTextField();
        txt_Age = new javax.swing.JTextField();
        txt_TelephoneNo = new javax.swing.JTextField();
        txt_Address = new javax.swing.JTextField();
        txt_Name = new javax.swing.JTextField();
        txt_EmployeeID = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        btn_OpenCamera = new javax.swing.JButton();
        btn_SendEmail = new javax.swing.JButton();
        btn_BrowseImage = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btn_UpdateImage = new javax.swing.JButton();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel5.setBackground(new java.awt.Color(51, 51, 51));

        buttonGroup1.add(rb_EmployeeID);
        rb_EmployeeID.setForeground(new java.awt.Color(255, 255, 255));
        rb_EmployeeID.setText("Employee ID");

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Search Employee details by click on Radio button and type a Keyword in below text field ");

        buttonGroup1.add(rb_EmployeeName);
        rb_EmployeeName.setForeground(new java.awt.Color(255, 255, 255));
        rb_EmployeeName.setText("Employee Name");

        buttonGroup1.add(rb_Address);
        rb_Address.setForeground(new java.awt.Color(255, 255, 255));
        rb_Address.setText("Address");

        buttonGroup1.add(rb_Age);
        rb_Age.setForeground(new java.awt.Color(255, 255, 255));
        rb_Age.setText("Age");

        txt_search.setBackground(new java.awt.Color(0, 153, 153));
        txt_search.setForeground(new java.awt.Color(0, 0, 0));
        txt_search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_searchKeyReleased(evt);
            }
        });

        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/suwasetha_pharmacy/icons8_Search_31px.png"))); // NOI18N

        tbl_employee.setBackground(new java.awt.Color(153, 153, 153));
        tbl_employee.setForeground(new java.awt.Color(255, 255, 255));
        tbl_employee.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_employee.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_employeeMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbl_employee);

        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Click on the table, row where you want to edit");

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/suwasetha_pharmacy/Employee.png"))); // NOI18N

        jButton2.setBackground(new java.awt.Color(0, 204, 204));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/suwasetha_pharmacy/Back.png"))); // NOI18N
        jButton2.setText("Main Menu");
        jButton2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(rb_EmployeeID)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rb_EmployeeName)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rb_Address)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rb_Age)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addComponent(txt_search, javax.swing.GroupLayout.PREFERRED_SIZE, 521, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel12)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 99, Short.MAX_VALUE)))
                        .addComponent(jLabel15)
                        .addGap(8, 8, 8)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rb_EmployeeID)
                            .addComponent(rb_EmployeeName)
                            .addComponent(rb_Address)
                            .addComponent(rb_Age)
                            .addComponent(jLabel14))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel15))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel12)))
                .addGap(25, 25, 25)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 487, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel13)
                        .addGap(0, 12, Short.MAX_VALUE))
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel4.setBackground(new java.awt.Color(51, 51, 51));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/suwasetha_pharmacy/Pharmacy.png"))); // NOI18N

        lbl_employeeImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/suwasetha_pharmacy/profilePic.png"))); // NOI18N
        lbl_employeeImage.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Employee ID");

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Name");

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Address");

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Telephone No");

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Email");

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Age");

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Join Date");

        btn_AddToEmployee.setBackground(new java.awt.Color(153, 153, 153));
        btn_AddToEmployee.setIcon(new javax.swing.ImageIcon(getClass().getResource("/suwasetha_pharmacy/Add.png"))); // NOI18N
        btn_AddToEmployee.setText("   ADD");
        btn_AddToEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AddToEmployeeActionPerformed(evt);
            }
        });

        btn_UpdateEmployee.setBackground(new java.awt.Color(153, 153, 153));
        btn_UpdateEmployee.setIcon(new javax.swing.ImageIcon(getClass().getResource("/suwasetha_pharmacy/Update.png"))); // NOI18N
        btn_UpdateEmployee.setText("UPDATE");
        btn_UpdateEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_UpdateEmployeeActionPerformed(evt);
            }
        });

        btn_DeleteFromEmployee.setBackground(new java.awt.Color(153, 153, 153));
        btn_DeleteFromEmployee.setIcon(new javax.swing.ImageIcon(getClass().getResource("/suwasetha_pharmacy/Delete.png"))); // NOI18N
        btn_DeleteFromEmployee.setText("DELETE");
        btn_DeleteFromEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_DeleteFromEmployeeActionPerformed(evt);
            }
        });

        btn_clear.setBackground(new java.awt.Color(153, 153, 153));
        btn_clear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/suwasetha_pharmacy/Clear.png"))); // NOI18N
        btn_clear.setText("CLEAR");
        btn_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clearActionPerformed(evt);
            }
        });

        txt_Qualifications.setBackground(new java.awt.Color(102, 102, 102));
        txt_Qualifications.setColumns(20);
        txt_Qualifications.setForeground(new java.awt.Color(255, 255, 255));
        txt_Qualifications.setRows(5);
        jScrollPane1.setViewportView(txt_Qualifications);

        txt_Email.setBackground(new java.awt.Color(102, 102, 102));
        txt_Email.setForeground(new java.awt.Color(255, 255, 255));

        txt_Age.setBackground(new java.awt.Color(102, 102, 102));
        txt_Age.setForeground(new java.awt.Color(255, 255, 255));

        txt_TelephoneNo.setBackground(new java.awt.Color(102, 102, 102));
        txt_TelephoneNo.setForeground(new java.awt.Color(255, 255, 255));

        txt_Address.setBackground(new java.awt.Color(102, 102, 102));
        txt_Address.setForeground(new java.awt.Color(255, 255, 255));

        txt_Name.setBackground(new java.awt.Color(102, 102, 102));
        txt_Name.setForeground(new java.awt.Color(255, 255, 255));

        txt_EmployeeID.setBackground(new java.awt.Color(102, 102, 102));
        txt_EmployeeID.setForeground(new java.awt.Color(255, 255, 255));

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Qualifications");

        btn_OpenCamera.setBackground(new java.awt.Color(153, 153, 153));
        btn_OpenCamera.setIcon(new javax.swing.ImageIcon(getClass().getResource("/suwasetha_pharmacy/cam.png"))); // NOI18N
        btn_OpenCamera.setText("Open Camera");
        btn_OpenCamera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_OpenCameraActionPerformed(evt);
            }
        });

        btn_SendEmail.setBackground(new java.awt.Color(153, 153, 153));
        btn_SendEmail.setIcon(new javax.swing.ImageIcon(getClass().getResource("/suwasetha_pharmacy/SendMail.png"))); // NOI18N
        btn_SendEmail.setText("Send Email");
        btn_SendEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SendEmailActionPerformed(evt);
            }
        });

        btn_BrowseImage.setBackground(new java.awt.Color(153, 153, 153));
        btn_BrowseImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/suwasetha_pharmacy/Browse.png"))); // NOI18N
        btn_BrowseImage.setText("Browse Image");
        btn_BrowseImage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_BrowseImageActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("EMPLOYEE PORTAL");

        btn_UpdateImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/suwasetha_pharmacy/Update.png"))); // NOI18N
        btn_UpdateImage.setText("UPDATE IMG");
        btn_UpdateImage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_UpdateImageActionPerformed(evt);
            }
        });

        jDateChooser1.setBackground(new java.awt.Color(102, 102, 102));
        jDateChooser1.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txt_Age, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_TelephoneNo, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_Name, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(btn_clear)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_DeleteFromEmployee)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_UpdateEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_AddToEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txt_EmployeeID, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel8)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txt_Email, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_SendEmail))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txt_Address, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel9))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 127, Short.MAX_VALUE)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_BrowseImage)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btn_OpenCamera, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                                    .addComponent(btn_UpdateImage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)))
                        .addComponent(lbl_employeeImage, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(6, 6, 6))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btn_OpenCamera, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(78, 78, 78)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btn_BrowseImage, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btn_UpdateImage, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(lbl_employeeImage, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(txt_EmployeeID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_Address, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_TelephoneNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_Age, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_Email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_SendEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btn_DeleteFromEmployee)
                                .addComponent(btn_clear))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btn_AddToEmployee)
                                .addComponent(btn_UpdateEmployee))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jLabel11)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(7, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbl_employeeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_employeeMouseClicked

        int row = tbl_employee.getSelectedRow();
        String tableClick = tbl_employee.getModel().getValueAt(row, 0).toString();

        Employee_Models objEmployee_Models = new Employee_Models();
        objEmployee_Models.setEmployeeID(tableClick);
        Employee_DB objEmployee_DB = new Employee_DB();
        ResultSet rs = objEmployee_DB.loadEmployeeTableID(objEmployee_Models);
        try {
            if (rs.next()) {

                txt_EmployeeID.setText(rs.getString("Employee_ID"));
                txt_Address.setText(rs.getString("Address"));
                int intAge = rs.getInt("Age");
                String strAge = String.valueOf(intAge);
                txt_Age.setText(strAge);
                txt_Name.setText(rs.getString("Employee_Name"));
                txt_Qualifications.setText(rs.getString("Qualifications"));
                txt_TelephoneNo.setText(rs.getString("Telephone_No"));
                txt_Email.setText(rs.getString("Email"));
                
                java.util.Date d = rs.getDate("Join_Date");
                jDateChooser1.setDate(d);
                

            } else {
                JOptionPane.showMessageDialog(null, "Error");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        loadImage();
    }//GEN-LAST:event_tbl_employeeMouseClicked

    private void txt_searchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_searchKeyReleased
        Employee_Models objEmployee_Models = new Employee_Models();
        String value = txt_search.getText();
        Employee_DB objEmployee_DB = new Employee_DB();

        if (rb_EmployeeID.isSelected()) {

            objEmployee_Models.setEmployeeID(value);
        } else if (rb_EmployeeName.isSelected()) {

            objEmployee_Models.setEmployeeName(value);
        } else if (rb_Address.isSelected()) {

            objEmployee_Models.setAddress(value);
        } else if (rb_Age.isSelected()) {
            int intValue = Integer.parseInt(value);
            objEmployee_Models.setAge(intValue);
        } else {
            JOptionPane.showMessageDialog(null, "Please select a Button before you search");
        }
        ResultSet rs = objEmployee_DB.getSearchDetails(objEmployee_Models);
        tbl_employee.setModel(DbUtils.resultSetToTableModel(rs));

    }//GEN-LAST:event_txt_searchKeyReleased

    private void btn_BrowseImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_BrowseImageActionPerformed

        JFileChooser filechooser = new JFileChooser();
        filechooser.setCurrentDirectory(new File(System.getProperty("user.home")));
        FileNameExtensionFilter filter = new FileNameExtensionFilter("*.IMAGE", "jpg", "png");
        filechooser.addChoosableFileFilter(filter);
        int result = filechooser.showSaveDialog(null);
        if (result == JFileChooser.APPROVE_OPTION) {
            File selectedFile = filechooser.getSelectedFile();
            String path = selectedFile.getAbsolutePath();
            lbl_employeeImage.setIcon(ResizeImage(path));
            s = path;

            try {
                File image = new File(s);
                FileInputStream fis = new FileInputStream(image);
                ByteArrayOutputStream bos = new ByteArrayOutputStream();
                byte[] buf = new byte[2000000];//Image size in bytes 
                for (int readNum; (readNum = fis.read(buf)) != -1;) {
                    bos.write(buf, 0, readNum);
                }
                employeeImage = bos.toByteArray();

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Your Image is too large");
            }

        } else if (result == JFileChooser.CANCEL_OPTION) {
            JOptionPane.showMessageDialog(null, "No Data");
        }
    }//GEN-LAST:event_btn_BrowseImageActionPerformed

    private void btn_SendEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SendEmailActionPerformed

        String getEmailAddress = txt_Email.getText();

        new EmailPortal(getEmailAddress).setVisible(true);
    }//GEN-LAST:event_btn_SendEmailActionPerformed

    private void btn_OpenCameraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_OpenCameraActionPerformed

        WebCamera objWebCamera = new WebCamera();
        objWebCamera.setVisible(true);
    }//GEN-LAST:event_btn_OpenCameraActionPerformed

    private void btn_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clearActionPerformed
        txt_Address.setText("");
        txt_Age.setText("");
        txt_Email.setText("");
        txt_EmployeeID.setText("");
        txt_Name.setText("");
        txt_Qualifications.setText("");
        txt_TelephoneNo.setText("");
    }//GEN-LAST:event_btn_clearActionPerformed

    private void btn_DeleteFromEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_DeleteFromEmployeeActionPerformed
        String getEmployeeID = txt_EmployeeID.getText();

        Employee_Models objEmployee_Models = new Employee_Models();
        objEmployee_Models.setEmployeeID(getEmployeeID);
        Employee_DB objEmployee_DB = new Employee_DB();

        int x = objEmployee_DB.deleteEmployee(objEmployee_Models);
        if (x == 1) {
            JOptionPane.showMessageDialog(null, "Successfully Deleted");

        } else {
            JOptionPane.showMessageDialog(null, "Not Deleted");
        }
        loadEmployeeTable();
    }//GEN-LAST:event_btn_DeleteFromEmployeeActionPerformed

    private void btn_UpdateEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_UpdateEmployeeActionPerformed
        String getEmployeeID = txt_EmployeeID.getText();
        String getName = txt_Name.getText();
        String getAddress = txt_Address.getText();
        String getTelephoneNo = txt_TelephoneNo.getText();
        String getEmail = txt_Email.getText();
        String getStrAge = txt_Age.getText();
        String getQualifications = txt_Qualifications.getText();
        java.util.Date d = jDateChooser1.getDate();
        java.sql.Date sqldate = new java.sql.Date(d.getTime());

        //byte[] getImage = employeeImage;
        int getIntAge = Integer.parseInt(getStrAge);

        Employee_Models objEmployee_Models = new Employee_Models(getEmployeeID, getName, getAddress, getTelephoneNo, getEmail, getIntAge, sqldate, getQualifications);
        Employee_DB objEmployee_DB = new Employee_DB();

        int x = objEmployee_DB.updateEmployee(objEmployee_Models);

        if (x == 1) {
            JOptionPane.showMessageDialog(null, "Successfully updaeted");

        } else {
            JOptionPane.showMessageDialog(null, "Not updated");
        }
        loadEmployeeTable();
    }//GEN-LAST:event_btn_UpdateEmployeeActionPerformed

    private void btn_AddToEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AddToEmployeeActionPerformed

        try {

            String getEmployeeID = txt_EmployeeID.getText();
            String getName = txt_Name.getText();
            String getAddress = txt_Address.getText();
            String getTelephoneNo = txt_TelephoneNo.getText();
            String getEmail = txt_Email.getText();
            String getStrAge = txt_Age.getText();
            String getQualifications = txt_Qualifications.getText();
            byte[] getImage = employeeImage;
            java.util.Date d = jDateChooser1.getDate();
            java.sql.Date sqldate = new java.sql.Date(d.getTime());

            int getIntAge = Integer.parseInt(getStrAge);

            Employee_Models objEmployee_Models = new Employee_Models(getEmployeeID, getName, getAddress, getTelephoneNo, getEmail, getIntAge, sqldate, getQualifications);
            objEmployee_Models.setImage(getImage);
            Employee_DB objEmployee_DB = new Employee_DB();
            int x = objEmployee_DB.insertEmployee(objEmployee_Models);

            if (x == 1) {
                JOptionPane.showMessageDialog(null, "Inserted Successfull");

            } else {
                JOptionPane.showMessageDialog(null, "Not Inserted");

            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Please fill all the fields");

        }
        loadEmployeeTable();
    }//GEN-LAST:event_btn_AddToEmployeeActionPerformed

    private void btn_UpdateImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_UpdateImageActionPerformed
        byte[] getImage = employeeImage;
        String employeeID = txt_EmployeeID.getText();

        Employee_Models objEmployee_Models = new Employee_Models();
        objEmployee_Models.setImage(getImage);
        objEmployee_Models.setEmployeeID(employeeID);

        Employee_DB objEmployee_DB = new Employee_DB();
        int x = objEmployee_DB.updateImage(objEmployee_Models);

        if (x == 1) {
            JOptionPane.showMessageDialog(null, "Successfully updated");

        } else {
            JOptionPane.showMessageDialog(null, "Not updated");
        }
        loadEmployeeTable();

    }//GEN-LAST:event_btn_UpdateImageActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       Main objMain = new Main();
       objMain.setVisible(true);
       this.hide();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        System.loadLibrary(Core.NATIVE_LIBRARY_NAME);
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Employee_Views.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Employee_Views.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Employee_Views.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Employee_Views.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Employee_Views().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_AddToEmployee;
    private javax.swing.JButton btn_BrowseImage;
    private javax.swing.JButton btn_DeleteFromEmployee;
    private javax.swing.JButton btn_OpenCamera;
    private javax.swing.JButton btn_SendEmail;
    private javax.swing.JButton btn_UpdateEmployee;
    private javax.swing.JButton btn_UpdateImage;
    private javax.swing.JButton btn_clear;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton2;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbl_employeeImage;
    private javax.swing.JRadioButton rb_Address;
    private javax.swing.JRadioButton rb_Age;
    private javax.swing.JRadioButton rb_EmployeeID;
    private javax.swing.JRadioButton rb_EmployeeName;
    private javax.swing.JTable tbl_employee;
    private javax.swing.JTextField txt_Address;
    private javax.swing.JTextField txt_Age;
    private javax.swing.JTextField txt_Email;
    private javax.swing.JTextField txt_EmployeeID;
    private javax.swing.JTextField txt_Name;
    private javax.swing.JTextArea txt_Qualifications;
    private javax.swing.JTextField txt_TelephoneNo;
    private javax.swing.JTextField txt_search;
    // End of variables declaration//GEN-END:variables
}
